#!/bin/php
<?php

$possibilities = [
    __DIR__ . "/vendor/autoload.php", // chamada na biblioteca
    __DIR__ . "/../../../vendor/autoload.php", // chamado no projeto
];

foreach ($possibilities as $autoloadPath) {
    if (file_exists($autoloadPath) === true) {
        require $autoloadPath;
        
        break;
    }
}

use Iquety\Console\Terminal;
use Iquety\PubSub\EventLoop;

// O PHP em modo CLI disponibiliza a variável reservada "$argv", contendo a lista 
// de palavras digitadas pelo usuário no Terminal. Esta variável será usada para
// passar as informações ao Terminal da biblioteca.

// Remove o primeiro argumento, que contém o nome do script (ex: ./example)
array_shift($argv);

$terminal = new Terminal(__DIR__ . "/src");

$terminal->loadRoutinesFrom(EventLoop::routinePath());

// Usa a variável $argv para interpretar os argumentos do usuário
$terminal->run($argv);
