#!/bin/bash
#
# ./composer - Acesso ao composer dockerizado 
#
# Este programa executa comandos do composer que está localizado dentro do conteiner
# docker, dispensando a necessidade de instalar o composer no computador local

PHP_CONTAINER='iquety-pubsub'

docker-compose up -d

if [ "$1" == "analyse" ] && [ "$1" == "--lint" ]; then
    docker run \
        -e RUN_LOCAL=true \
        -e VALIDATE_MARKDOWN=true \
        -e MARKDOWN_CONFIG_FILE="docs/.lint.yml" \
        -e FILTER_REGEX_INCLUDE="/.*" \
        -v "$(pwd)/docs/.lint.yml":"/action/lib/.automation/docs/.lint.yml" \
        -v "$(pwd)":"/tmp/lint" github/super-linter
        
    exit 0;
fi

if [ "$1" == "lint" ]; then
    exit;
fi 

if [ "$1" == "bash" ]; then
    docker exec -it $PHP_CONTAINER bash

    exit 0
fi

if [ "$1" == "supervisor" ] && [ "$2" == "restart" ]; then
    docker exec -it $PHP_CONTAINER service supervisor restart

    exit 0
fi

if [ "$1" == "supervisor" ] && [ "$2" == "stop" ]; then
    docker exec -it $PHP_CONTAINER service supervisor stop

    exit 0
fi

if [ "$1" == "supervisor" ] && [ "$2" == "start" ]; then
    docker exec -it $PHP_CONTAINER service supervisor start
    
    exit 0
fi

docker exec -it $PHP_CONTAINER \
    composer $@
