#!/bin/php
<?php

// Carrega o autoloader do Composer
include __DIR__ . "/vendor/autoload.php";

use Iquety\Console\Terminal;
use Iquety\PubSub\EventLoop;

// O PHP em modo CLI disponibiliza a variável reservada "$argv", contendo a lista 
// de palavras digitadas pelo usuário no Terminal. Esta variável será usada para
// passar as informações ao Terminal da biblioteca.

// Remove o primeiro argumento, que contém o nome do script (ex: ./example)
array_shift($argv);

$terminal = new Terminal(__DIR__ . "/src");

$terminal->loadRoutinesFrom(EventLoop::routinePath());

// Usa a variável $argv para interpretar os argumentos do usuário
$terminal->run($argv);
